version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html
hooks:
   BeforeInstall:
    - location: scripts/installbundle.sh
      runas: root
    - location: scripts/startrails.sh
      runas: root
   AfterInstall:
    - location: scripts/restartrails.sh
      runas: root
