version :  0.0 
os :  linux 
Files : 
  - source :  ruby3/app/views/welcome/index.erb
    destination :  /var/www/html/ 
Hooks : 
  BeforeInstall : 
    - location :  scripts/Install_dependencies 
      timeout :  300 
      runas :  root 
    - location :  scripts/start_server 
      timeout :  300 
      runas :  root 
  ApplicationStop : 
    - location :  scripts/STOP_SERVER 
      timeout :  300 
      runas :  root
