version: 0.0
os: linux
files:
  - source: source
    destination: /var/www/ruby3
permissions:
   - object: /var/www/
     pattern: "**"
     mode: 775
hooks:
   ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
