version: 0.0
os: linux
files:
  - source: \
    destination: /var/www/ruby3
permissions:
   - object: /var/www/
     pattern: "**"
     mode: 775
hooks:
   BeforeInstall:
    - location: scripts/bundle_install.sh
      runas: root
    - location: scripts/start_server.sh
      runas: root
   AfterInstall:
    - location: scripts/restart_server.sh
      runas: root
