version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ruby3
permissions:
   - object: /var/www/
     pattern: "**"
     mode: 775
     acls: 
      - u:ubuntu:rw
hooks:
   AfterInstall:
    - location: scripts/bundle_install.sh
      timeout: 300
   ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
