version: 0.0
os: linux
files:
  - Source: /ruby3/
    destination: /home/ubuntu/tmp/
permissions:
   - Object: /home/ubuntu/
     pattern: "**"
     mode: 775
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/bundle_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
